import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import logoImg from '../../assets/images/logo_banner.png';
import { Container } from '../../styles/pages/homePageStyle';
import { Header } from '../../components/Header'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <Container>
            <div>
              <Image src={logoImg} alt="Logo" />
            </div>

            <div>Acontecendo Agora</div>

            <div>Eventos interativos agora</div>

            <div>Eventos interativos que já passaram</div>
        </Container>
      </main>

      <footer>
          Teste
      </footer>
    </div>
  )
}

export default Home
