/* eslint-disable jsx-a11y/label-has-associated-control */
import React, { FormEvent, useState } from 'react';
import Head from 'next/head';
import type { NextPage } from 'next';
import { Header } from '../../components/Header';
import { useAuth } from '../../hooks/useAuth';
import { database } from '../../services/firebase';

const CreateEvent: NextPage = () => {
  const { user } = useAuth();
  const [eventTitle, setEventTitle] = useState('');
  const [eventVideo, setEventVideo] = useState('');

  async function handleCreateNewEvent(event: FormEvent) {
    event.preventDefault();

    const roomRef = database.ref('events/');

    const newPushRef = await roomRef.push();
    const eventId = newPushRef.key;

    const roomInfo = {
      title: eventTitle,
      authorID: user?.id,
      youtubeLiveVideoId: eventVideo,
      scheduleDate: Date.now(),
      type: 'Audiência Pública',
      description: 'Uma descrição qualquer do evento e suas informações',
      status: 'Agendado',
      closedOn: null,
    };

    await database.ref(`events/${eventId}/info`).push(roomInfo);
  }

  const handleEventTitleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setEventTitle(e.currentTarget.value);
  };

  const handleEventVideoChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setEventVideo(e.currentTarget.value);
  };

  return (
    <div>
      <Head>
        <title>Criar Evento</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <div>
          <label htmlFor="name">Título</label>
          <input id="titulo" type="text" required onChange={handleEventTitleChange} />
          <label htmlFor="name">Video do Youtube</label>
          <input id="youtubeVideo" type="text" required onChange={handleEventVideoChange} />

          <button type="button" onClick={handleCreateNewEvent}>
            Cadastrar
          </button>
        </div>
      </main>
    </div>
  );
};

export default CreateEvent;
